# Generated by Django 3.2.5 on 2021-11-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSubscription',
            fields=[
                ('service_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('plans', models.CharField(max_length=128)),
                ('image_id', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'DefaultSubscription',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(help_text='user ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=256)),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_price', models.CharField(max_length=128)),
                ('cycle', models.CharField(max_length=128)),
                ('head_count', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(max_length=128)),
                ('service_id', models.CharField(max_length=128, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('share_id', models.CharField(max_length=128, null=True)),
                ('image_id', models.CharField(max_length=1024, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id_hee', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_price', models.IntegerField()),
                ('cycle', models.CharField(max_length=64)),
                ('default_sub_id', models.ForeignKey(db_column='default_sub_id', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.defaultsubscription')),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
    ]
